AdminPage/Controllers/BillController.cs
using CinemaObject;
using DataAccess.respository;
using DataAccess;
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using AdminPage.Models;

namespace AdminPage.Controllers
{
    public class BillController : Controller
    {
        IBillRepository billRepository = null;
        public BillController() => billRepository = new BillRepository();
        // GET: FastFoodController
        public ActionResult Index()
        {
            if (HttpContext.Session.GetString("Role") != "1")
            {
                TempData["NeedLoginToBooking"] = "Please login to your account for booking ticket";
                return Redirect("/Home/Login");
            }
            var billList = billRepository.GetBills();
            return View(billList);
        }

        // GET: FastFoodController/Details/5
        // POST: FastFoodController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Bill bill)
        {

            Console.WriteLine(bill.TicketId + " " + bill.IdMovie + " " + bill.FastFood + " " + bill.SeatNum + " " + bill.QuantityDrink + " " + bill.QuantityFastfood + " " + bill.TicketType + " " + bill.Drink);

            try
            {
                TicketDAO ticketDAO = new TicketDAO();
                FastFoodDAO fastFoodDAO = new FastFoodDAO();
                BillDAO billDAO = new BillDAO();
                Bill _bill = billDAO.GetBillByID(bill.Id);

                

                if (_bill == null)
                {
                    FastFood Food = fastFoodDAO.GetFastFoodByID(bill.FastFood);
                    FastFood Drink = fastFoodDAO.GetFastFoodByID(bill.Drink);
                    Ticket ticket = ticketDAO.GetTicketByID(bill.TicketId);

                    bill.TicketType = ticket.TicketType;
                    bill.Total = 0;

                    bill.BookingDate = DateTime.Today;
                    bill.Total = ticket.Price + Food.Price * bill.QuantityFastfood + Drink.Price * bill.QuantityDrink;
                    Console.WriteLine(bill.TicketId + " " + bill.IdMovie + " " + bill.FastFood + " " + bill.SeatNum + " " + bill.QuantityDrink + " " + bill.QuantityFastfood + " " + bill.TicketType + " " + bill.Total + " " + bill.Drink);
                    using var context = new CinemaProject_v4Context();
                    context.Bills.Add(bill);
                    context.SaveChanges();
                }
                else
                {
                    throw new Exception("The fast food is already exist.");
                }
                if (_bill != null)
                {
                    billRepository.InsertBill(bill);
                }
                return Redirect("/Home/Index");
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: FastFoodController/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var bill = billRepository.GetBillByID(id.Value);
            if (bill == null)
            {
                return NotFound();
            }
            return View(bill);
        }

        // POST: FastFoodController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Bill bill)
        {
            try
            {
                if (id != bill.Id)
                    return NotFound();
                if (ModelState.IsValid)
                    billRepository.UpdateBill(bill);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }

        // GET: FastFoodController/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var bill = billRepository.GetBillByID(id.Value);
            if (bill == null)
                return NotFound();
            return View(bill);
        }

        // POST: FastFoodController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                billRepository.DeleteBill(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }
    }
}

AdminPage/Controllers/StaffController.cs
using CinemaObject;
using DataAccess.respository;
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AdminPage.Controllers
{
    public class StaffController : Controller
    {
        IStaffRepository staffRepository = null;
        public StaffController() => staffRepository = new StaffRepository();
        // GET: MovieController
        public ActionResult Index()
        {
            if (HttpContext.Session.GetString("Role") != "1")
            {
                TempData["NeedLoginToBooking"] = "Please login to your account for booking ticket";
                return Redirect("/Home/Login");
            }
            var staffList = staffRepository.GetStaffs();
            return View(staffList);
        }

        // GET: MovieController/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var staff = staffRepository.GetStaffByID(id.Value);
            if (staff == null)
            {
                return NotFound();
            }
            return View(staff);
        }

        // GET: MovieController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MovieController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(staff staff)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    staff.Status = 1;
                    staffRepository.InsertStaff(staff);
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(staff);
            }
        }

        // GET: MovieController/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var staff = staffRepository.GetStaffByID(id.Value);
            if (staff == null)
            {
                return NotFound();
            }
            return View(staff);
        }

        // POST: MovieController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, staff staff)
        {
            try
            {
                if (id != staff.Id)
                {
                    return NotFound();
                }
                if (ModelState.IsValid)
                {
                    staffRepository.UpdateStaff(staff);
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }

        // GET: MovieController/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var staff = staffRepository.GetStaffByID(id.Value);
            if (staff == null)
            {
                return NotFound();
            }
            return View(staff);
        }

        // POST: MovieController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                staffRepository.DeleteStaff(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }
    }
}

AdminPage/Controllers/TicketController.cs
using CinemaObject;
using DataAccess.respository;
using DataAccess;
using System.Collections.Generic;
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using AdminPage.Models;

namespace AdminPage.Controllers
{
    public class TicketController : Controller
    {
        ITicketRepository ticketRepository = null;
        public TicketController() => ticketRepository = new TicketRepository();
        // GET: FastFoodController
        public ActionResult Index()
        {
            if (HttpContext.Session.GetString("Role") != "1")
            {
                TempData["NeedLoginToBooking"] = "Please login to your account for booking ticket";
                return Redirect("/Home/Login");
            }
            var ticketList = ticketRepository.GetTickets();
            return View(ticketList);
        }

        // GET: FastFoodController/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var ticket = ticketRepository.GetTicketByID(id.Value);
            if (ticket == null)
            {
                return NotFound();
            }
            return View(ticket);
        }

        // GET: FastFoodController/Create
        [HttpGet]
        public ActionResult Create()
        {
            MovieDAO movieDAO = new MovieDAO();
            ViewCreateTicketModel viewCreateTicketModel = new ViewCreateTicketModel();
            viewCreateTicketModel.Movies = movieDAO.GetMovieList();
            return View(viewCreateTicketModel);
        }

        // POST: FastFoodController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Ticket ticket)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ticketRepository.InsertTicket(ticket);
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(ticket);
            }
        }

        // GET: FastFoodController/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var ticket = ticketRepository.GetTicketByID(id.Value);
            if (ticket == null)
            {
                return NotFound();
            }
            return View(ticket);
        }

        // POST: FastFoodController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Ticket ticket)
        {
            try
            {
                if (id != ticket.Id)
                    return NotFound();
                if (ModelState.IsValid)
                    ticketRepository.UpdateTicket(ticket);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }

        // GET: FastFoodController/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var ticket = ticketRepository.GetTicketByID(id.Value);
            if (ticket == null)
                return NotFound();
            return View(ticket);
        }

        // POST: FastFoodController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                ticketRepository.DeleteTicket(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }

        [HttpGet]
        public ActionResult Order()
        {
            var ticketList = ticketRepository.GetTickets();
            return View(ticketList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Order(int? id)
        {
            string txt = "";
            var options = new CookieOptions
            {
                Expires = DateTime.Now.AddDays(1)
            };
            if (Request.Cookies["ticket"] == null)
            {
                txt = id + ":1";
                Response.Cookies.Append("ticket", txt, options);
            }
            else
            {
                TicketDAO ticketDAO = new TicketDAO();
                txt = Convert.ToString(Request.Cookies["ticket"]);
                Response.Cookies.Append("ticket", "", options);
                string[] t = txt.Split(";");
                var ticketList = new List<Ticket>();
                for (int i = 0; i < t.Length; i++)
                {
                    string[] a = t[i].Split(":");
                    Ticket ticket = new Ticket();
                    ticket = ticketDAO.GetTicketByID(Convert.ToInt32(a[0]));
                    ticket.Quantity = Convert.ToInt32(a[1]);
                    ticketList.Add(ticket);
                }

                int check = 0;

                foreach (Ticket ticket in ticketList)
                {
                    if (ticket.Id == id)
                    {
                        ticket.Quantity++;
                        check = 1;
                        break;
                    }
                }

                txt = ticketList[0].Id + ":" + ticketList[0].Quantity;

                for (int i = 1; i < ticketList.Count; i++)
                {
                    txt += ";" + ticketList[i].Id + ":" + ticketList[i].Quantity;
                }
                if (check == 0)
                {
                    txt += ";" + id + ":1";
                }

                Response.Cookies.Append("ticket", txt, options);
            }
            var tickets = ticketRepository.GetTickets();
            return View(tickets);
        }
    }
}

AdminPage/Controllers/TurnoverController.cs
using CinemaObject;
using DataAccess;
using AdminPage.Models;
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AdminPage.Controllers
{
    public class TurnoverController : Controller
    {
        public ActionResult Index()
        {
            if (HttpContext.Session.GetString("Role") != "1")
            {
                TempData["NeedLoginToBooking"] = "Please login to your account for booking ticket";
                return Redirect("/Home/Login");
            }
            TicketDAO ticketDAO = new TicketDAO();
            FastFoodDAO fastFoodDAO = new FastFoodDAO();
            BillDAO billDAO = new BillDAO();

            var billList = billDAO.GetBills();

            TurnoverModel turnover = new TurnoverModel();

            DateTime today = DateTime.Today;

            int month = today.Month;
            int year = today.Year;

            turnover.month = month;
            turnover.year = year;

            turnover.mfTotal = 0;
            turnover.mtTotal = 0;
            turnover.yfTotal = 0;

            foreach (var bill in billList)
            {
                if (bill.BookingDate.Month == month && bill.BookingDate.Year == year)
                {
                    FastFood food = fastFoodDAO.GetFastFoodByID(bill.FastFood);
                    FastFood drink = fastFoodDAO.GetFastFoodByID(bill.Drink);
                    Ticket ticket = ticketDAO.GetTicketByID(bill.TicketId);

                    turnover.mfTotal += food.Price * bill.QuantityFastfood + drink.Price * bill.QuantityDrink;
                    turnover.mtTotal += ticket.Price;
                }
                if (bill.BookingDate.Year == year)
                {
                    FastFood food = fastFoodDAO.GetFastFoodByID(bill.FastFood);
                    FastFood drink = fastFoodDAO.GetFastFoodByID(bill.Drink);
                    Ticket ticket = ticketDAO.GetTicketByID(bill.TicketId);

                    turnover.yfTotal += food.Price * bill.QuantityFastfood + drink.Price * bill.QuantityDrink;
                    turnover.ytTotal += ticket.Price;
                }
            }

            return View(turnover);
        }

        // GET: TurnoverController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
    }
}

AdminPage/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <title>One Movies an Entertainment Category Flat Bootstrap Responsive Website Template | Home :: w3layouts</title>
    <!-- for-mobile-apps -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords"
          content="One Movies Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript">
        addEventListener("load", function() {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!-- //for-mobile-apps -->
    <link href="~/assets/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/assets/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link rel="stylesheet" href="~/assets/css/contactstyle.css" type="text/css" media="all" />
    <link rel="stylesheet" href="~/assets/css/faqstyle.css" type="text/css" media="all" />
    <link href="~/assets/css/single.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/medile.css" rel="stylesheet" type="text/css" />
    <!-- banner-slider -->
    <link href="~/assets/css/jquery.slidey.min.css" rel="stylesheet" />
    <!-- //banner-slider -->
    <link rel="stylesheet" href="~/assets/list-css/list.css" type="text/css" media="all" />
    <link rel="stylesheet" href="~/assets/news-css/news.css" type="text/css" media="all" />

    <!-- pop-up -->
    <link href="~/assets/css/popuo-box.css" rel="stylesheet" type="text/css" media="all" />
    <!-- //pop-up -->
    <!-- font-awesome icons -->
    <link rel="stylesheet" href="~/assets/css/font-awesome.min.css" />
    <!-- //font-awesome icons -->
    <!-- js -->
    <script type="text/javascript" src="~/assets/js/jquery-2.1.4.min.js"></script>
    <!-- //js -->
    <!-- banner-bottom-plugin -->
    <link href="~/assets/css/owl.carousel.css" rel="stylesheet" type="text/css" media="all" />
    <script src="~/assets/js/owl.carousel.js"></script>
    <script>
        $(document).ready(function () {
            $("#owl-demo").owlCarousel({

                autoPlay: 3000, //Set AutoPlay to 3 seconds

                items: 5,
                itemsDesktop: [640, 4],
                itemsDesktopSmall: [414, 3]

            });

        });
    </script>
    <!-- //banner-bottom-plugin -->
    <link href="//fonts.googleapis.com/css?family=Roboto+Condensed:400,700italic,700,400italic,300italic,300" rel="stylesheet" type="text/css" />
    <!-- start-smoth-scrolling -->
    <script type="text/javascript" src="~/assets/js/move-top.js"></script>
    <script type="text/javascript" src="~/assets/js/easing.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({
                    scrollTop: $(this.hash).offset().top
                }, 1000);
            });
        });
    </script>
    <!-- start-smoth-scrolling -->
    <!-- tables -->
    <link rel="stylesheet" type="text/css" href="~/assets/list-css/table-style.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/list-css/basictable.css" />
    <script type="text/javascript" src="~/assets/list-js/jquery.basictable.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#table').basictable();

            $('#table-breakpoint').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint1').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint2').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint3').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint4').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint5').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint6').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint7').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint8').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint9').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint10').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint11').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint12').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint13').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint14').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint15').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint16').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint17').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint18').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint19').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint20').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint21').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint22').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint23').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint24').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint25').basictable({
                breakpoint: 768
            });
            $('#table-breakpoint26').basictable({
                breakpoint: 768
            });
        });
    </script>

    <!--CSS for Data table-->
    <style>
        .dataTables_length,
        .dataTables_filter {
            padding: 10px 0px;
            font-size: 20px;
            text-align: center;
        }

            .dataTables_filter label input {
                margin-left: 12px;
                border-radius: 30px;
                text-indent: 8px;
            }

        .dataTables_info {
            text-align: center;
            padding: 10px 0;
            font-size: 20px;
        }

        .dataTables_paginate {
            text-align: center;
            padding: 10px 0;
            font-size: 20px;
        }

        .paginate_button {
            margin: 0px 4px;
        }

            .paginate_button:hover {
                cursor: pointer;
            }
    </style>
</head>
<body>
    <!-- header -->
    <div class="header">
        <div class="container">
            <div class="w3layouts_logo">
                <a asp-action="Index" asp-controller="Home">
                    <h3 style="font-size: 34px;" class="text-center">High<span>Movies</span></h3>
                </a>
            </div>
            <div class="w3_search">
                @using (Html.BeginForm("Search", "Home", FormMethod.Post))
                {

                    <input type="text" id="Search" name="Search" placeholder="Search Movie By Name" required />
                    <input type="submit" value="Go" />
                }
            </div>
            <div class="w3l_sign_in_register">
                <ul>
                    <li><i class="fa fa-phone" aria-hidden="true"></i> 0845914368</li>

                    @{
                        if (@HttpContextAccessor.HttpContext.Session.GetString("Username") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                            </li>
                        }
                    }
                </ul>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <!-- nav -->
    <div class="movies_nav">
        <div class="container">
            <nav class="navbar navbar-default">
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="navbar-collapse navbar-right collapse" id="bs-example-navbar-collapse-1">
                    <nav>
                        <ul class="nav navbar-nav" style="display: flex; justify-content: center; align-items: center;">
                            <li class="nav-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Account</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Staff" asp-action="Index">Staff</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movie</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="FastFood" asp-action="Index">FastFood</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Ticket" asp-action="Index">Ticket</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bill" asp-action="Index">Bill</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Turnover" asp-action="Index">Turnover</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </nav>
        </div>
    </div>
    <!--  nav -->

    <div class="container">
        <main role="main" class="">@RenderBody()</main>
    </div>

    <!-- footer -->
    <footer>
        <div class="footer">
            <div class="container">
                <div class="w3ls_footer_grid">
                    <div class="col-md-6 w3ls_footer_grid_left">
                        <div class="w3ls_footer_grid_left1">
                            <h2>Subscribe to us</h2>
                            <div class="w3ls_footer_grid_left1_pos">
                                <form action="#" method="post">
                                    <input type="email" name="email" placeholder="Your email..." required="">
                                    <input type="submit" value="Send">
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 w3ls_footer_grid_right">
                        <a href="index.html">
                            <h2 style="padding-right: 77px;font-size: 40px;width: 160px;">
                                High
                                <span>Movies</span>
                            </h2>
                        </a>
                    </div>
                    <div class="clearfix"> </div>
                </div>
                <div class="col-md-5 w3ls_footer_grid1_left">
                    <p>
                        &copy; 2022 High Movies. All rights reserved | Design by <a href="#">HighGroup</a>
                    </p>
                </div>
                <div class="col-md-7 w3ls_footer_grid1_right">
                    <ul>
                        <li>
                            <a href="genres.html">Movies</a>
                        </li>
                        <li>
                            <a href="faq.html">FAQ</a>
                        </li>
                        <li>
                            <a href="horror.html">Genres</a>
                        </li>
                        <li>
                            <a href="contact.html">Contact Us</a>
                        </li>
                    </ul>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
        <!--End: Footer-->
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>